/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StakeLazyImport = createFileRoute('/stake')()
const DepositLazyImport = createFileRoute('/deposit')()
const ClaimLazyImport = createFileRoute('/claim')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StakeLazyRoute = StakeLazyImport.update({
  path: '/stake',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/stake.lazy').then((d) => d.Route))

const DepositLazyRoute = DepositLazyImport.update({
  path: '/deposit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/deposit.lazy').then((d) => d.Route))

const ClaimLazyRoute = ClaimLazyImport.update({
  path: '/claim',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/claim.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimLazyImport
      parentRoute: typeof rootRoute
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositLazyImport
      parentRoute: typeof rootRoute
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ClaimLazyRoute,
  DepositLazyRoute,
  StakeLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/claim",
        "/deposit",
        "/stake"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/claim": {
      "filePath": "claim.lazy.tsx"
    },
    "/deposit": {
      "filePath": "deposit.lazy.tsx"
    },
    "/stake": {
      "filePath": "stake.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
